version: "3"
services:
  php:
    build:
      context: ./bin/php/${PHP_VERSION}
      args:
        PHP_VERSION: ${PHP_VERSION}
        TZ: "$TZ"
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        EXTENSIONS: ${EXTENSIONS}
    container_name: ${PHP_CONTAINER_NAME}
    restart: 'always'
    cap_add:
          - SYS_PTRACE
    ports:
      - "${PHP_PORT}:9000"
    networks:
      - ${NETWORK}
    volumes:
          - ${WWW}:/var/www/html/:rw
          - ${PHP_FPM_CONF}:/usr/local/etc/php-fpm.d/www.conf:rw
          - ${PHP_INI}:/usr/local/etc/php/php.ini:ro
          - ${PHP_LOG}:/var/log/php

  nginx:
    image: nginx:${NGINX_VERSION}-alpine
    container_name: ${NGINX_CONTAINER_NAME}
    environment:
      TZ: "$TZ"
    restart: 'always'
    networks:
      - ${NETWORK}
    volumes:
      - ${WWW}:/var/www/html/:rw
      - ${NGINX_CONFD}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG}:/var/log/nginx/:rw
    ports:
          - "${NGINX_HTTP_PORT}:80"
          - "${NGINX_HTTPS_PORT}:443"

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_CONF}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA}:/var/lib/mysql/:rw  #include mysql log
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
    networks:
      - ${NETWORK}

  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_CONF}:/etc/redis.conf:ro
      - ${REDIS_DATA}:/data:rw
      - ${REDIS_LOG}:/var/log/redis/:rw
    restart: 'always'
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      - ${NETWORK}

  rabbit:
    image: rabbitmq:management
    container_name: ${RABBITMQ_CONTAINER_NAME}
    privileged: true
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
      - ${RABBITMQ_AMQP_PORT_1}:5672
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      TZ: "$TZ"
    volumes:
      - ${RABBITMQ_CONF}:/etc/rabbitmq:rw
      - ${RABBITMQ_LOG}:/var/log/rabbitmq:rw
      - ${RABBITMQ_DATA}:/var/lib/rabbitmq:rw
    restart: 'always'
    networks:
      - ${NETWORK}

