name: deploy

on:
  push:
    paths: 
      - '.env'
      - 'docker-compose.yml'
      - 'bin/**'
      - 'config/**'
      - 'data/**'
      - 'logs/**'
    branches: [ master ]
  pull_request:
    paths: 
      - '.env'
      - 'docker-compose.yml'
      - 'bin/**'
      - 'config/**'
      - 'data/**'
      - 'logs/**'
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: docker-compose up
        run: |
          docker-compose up -d
          docker-compose ps
      - name: tests
        run: sudo sh ./.github/workflows/tests.sh
