name: deploy

on:
  push:
    paths: 
      - '.env'
      - 'docker-compose.yml'
      - 'bin/**'
      - 'config/**'
      - 'data/**'
      - 'logs/**'
    branches: [ master ]
  pull_request:
    paths: 
      - '.env'
      - 'docker-compose.yml'
      - 'bin/**'
      - 'config/**'
      - 'data/**'
      - 'logs/**'
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: use dp
        uses: ./.github/workflows/deploy.yml
      - name: test php
        run: if [ "`docker inspect --format '{{.State.Running}}' dp_php`" == "true" ]; then ls error; fi
